# Generated by Django 4.2.10 on 2024-03-09 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_measurement_unit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('id',), 'verbose_name': 'ингридиенты', 'verbose_name_plural': 'ингридиенты'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-published',), 'verbose_name': 'рецепт', 'verbose_name_plural': 'рецепты'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['id'], name='recipes_ing_id_14c23f_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['id'], name='recipes_rec_id_f136e7_idx'),
        ),
    ]
