# Generated by Django 4.2.10 on 2024-03-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_remove_shoppingcart_unique_recipes_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_carts',
        ),
    ]
