# Generated by Django 4.2.10 on 2024-03-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.UniqueConstraint(fields=('follower', 'follow_to'), name='unique_subscribtion'),
        ),
    ]
